BRAND_ALIAS_GROUPS = [

    # GLOBAL SOCIAL / MESSAGING / GOOGLE / AI
    ("youtube", "you tube", "yt", "يوتيوب", "يوتوب", "يوتيب"),
    ("instagram", "insta", "ig", "انستغرام", "انستقرام", "انستا"),
    ("whatsapp", "whats app", "واتساب", "واتس اب", "واتسآب"),
    ("telegram", "تلجرام", "تليجرام", "تيليجرام"),
    ("tiktok", "tik tok", "تيك توك", "تيكتوك"),
    ("facebook", "fb", "فيسبوك", "فيس بوك"),
    ("messenger", "facebook messenger", "ماسنجر", "مسنجر"),
    ("snapchat", "snap chat", "snap", "سناب شات", "سناب"),
    ("x", "twitter", "تويتر", "اكس", "إكس"),
    ("threads", "ثريدز", "ثريد"),
    ("reddit", "ريديت"),
    ("discord", "ديسكورد"),
    ("linkedin", "linked in", "لينكد ان", "لينكدإن"),
    ("pinterest", "بنترست", "بينترست"),
    ("gmail", "google mail", "جي ميل", "جيميل"),
    ("google chrome", "chrome", "كروم", "جوجل كروم", "غوغل كروم"),
    ("google maps", "maps", "خرائط", "خرائط جوجل", "خرائط غوغل"),
    ("google drive", "drive", "درايف", "جوجل درايف"),
    ("google photos", "photos", "صور جوجل", "جوجل فوتوز"),
    ("google translate", "translate", "ترجمة جوجل", "مترجم جوجل"),
    ("chatgpt", "chat gpt", "gpt", "شات جي بي تي", "تشات جي بي تي", "شات جبت"),
    ("gemini", "google gemini", "جيميني", "جمني"),
    ("copilot", "microsoft copilot", "كوبايلوت", "كو بايلوت"),
    ("zoom", "زووم"),
    ("google meet", "meet", "جوجل ميت", "غوغل ميت"),
    ("skype", "سكايب"),
    ("signal", "سيجنال", "سيغنال"),
    ("viber", "فايبر"),
    ("microsoft teams", "teams", "تيمز", "مايكروسوفت تيمز"),
    ("slack", "سلاك"),
    ("notion", "نوشن", "نوتشن"),
    ("canva", "كانفا"),
    ("capcut", "cap cut", "كاب كت", "كاب كات"),
    ("kinemaster", "kine master", "كين ماستر", "كاين ماستر"),
    ("inshot", "in shot", "ان شوت", "إن شوت"),
    ("picsart", "pics art", "بيكس ارت", "بيكس آرت"),
    ("adobe lightroom", "lightroom", "لايت روم", "لايتروم"),
    ("photoshop express", "adobe photoshop express", "فوتوشوب", "فوتوشوب اكسبريس"),
    ("snapseed", "snap seed", "سناب سيد", "سنابسيد"),
    ("vsco", "فيسكو", "فسكو"),
    ("vn video editor", "vn editor", "vn", "في ان", "في إن"),
    ("filmora", "filmorago", "filmora go", "فيلمورا", "فيلمورا جو"),
    ("powerdirector", "power director", "باور دايركتور"),
    ("spotify", "سبوتيفاي", "سبوتفي"),
    ("netflix", "نتفلكس", "نيتفليكس", "نتفليكس"),
    ("prime video", "amazon prime video", "برايم فيديو"),
    ("disney plus", "disney+", "ديزني بلس"),
    ("twitch", "تويتش"),
    ("soundcloud", "ساوند كلاود"),
    ("shazam", "شازام"),
    ("duolingo", "دوولينجو", "دولينجو"),

    # GLOBAL SHOPPING / FOOD / TRAVEL
    ("amazon", "amazon shopping", "امازون", "أمازون"),
    ("temu", "تيمو", "تيمو شوبينغ"),
    ("shein", "شي ان", "شي إن", "شين"),
    ("aliexpress", "ali express", "علي اكسبريس", "علي إكسبريس"),
    ("ebay", "ايباي", "إيباي"),
    ("etsy", "اتسي", "إتسي"),
    ("uber", "اوبر", "أوبر"),
    ("uber eats", "ubereats", "اوبر ايتس", "أوبر إيتس"),
    ("bolt", "بولت"),
    ("booking", "booking.com", "بوكينج", "بوكنق"),
    ("airbnb", "air bnb", "اير بي ان بي", "إير بي إن بي"),
    ("tripadvisor", "trip advisor", "تريب ادفايزر"),
    ("google wallet", "wallet", "محفظة جوجل"),
    ("apple pay", "ابل باي", "آبل باي"),
    ("paypal", "pay pal", "باي بال"),
    ("revolut", "ريفولوت"),
    ("wise", "transferwise", "وايز"),

    # GLOBAL GAMES
    ("clash of clans", "coc", "كلاش اوف كلانس", "كلاش أوف كلانس", "كلاش كلانس", "كلاش العشائر"),
    ("clash royale", "cr", "كلاش رويال", "كلاش رويالز"),
    ("brawl stars", "براول ستارز", "برول ستارز"),
    ("pubg mobile", "pubg", "ببجي", "بوبجي", "ببجي موبايل"),
    ("call of duty mobile", "cod mobile", "كول اوف ديوتي", "كول أوف ديوتي", "كود موبايل"),
    ("free fire", "فري فاير"),
    ("roblox", "روبلوكس", "روبلكس"),
    ("minecraft", "ماين كرافت", "ماينكرافت"),
    ("fortnite", "فورت نايت", "فورتنايت"),
    ("subway surfers", "صب واي سيرفرز", "سب واي سيرفرز"),
    ("candy crush", "كاندي كراش"),
    ("among us", "امونج اس", "أمونغ آس"),
    ("pokemon go", "بوكيمون جو"),
    ("genshin impact", "جينشن امباكت", "قنشن امباكت"),
    ("league of legends", "lol", "ليج اوف ليجندز"),
    ("wild rift", "وايلد ريفت"),
    ("fifa mobile", "fc mobile", "فيفا موبايل", "اف سي موبايل"),
    ("efootball", "pes", "اي فوتبول", "بيس"),
    ("8 ball pool", "ايت بول بول", "ثمانية بول"),

    # USA / ENGLISH-SPEAKING
    ("chase", "chase bank", "تشيس", "بنك تشيس"),
    ("bank of america", "boa", "بنك اوف امريكا", "بنك أوف أميركا"),
    ("wells fargo", "ويلز فارغو", "ويلز فارجو"),
    ("citibank", "citi", "سيتي بنك", "سيتي"),
    ("capital one", "كابيتال ون"),
    ("us bank", "u.s. bank", "يو اس بنك"),
    ("pnc bank", "pnc", "بي ان سي بنك"),
    ("truist", "تروست", "ترويست"),
    ("american express", "amex", "امريكان اكسبرس", "أمريكان إكسبريس"),
    ("discover", "ديسكفر"),
    ("venmo", "فينمو"),
    ("cash app", "كاش اب", "كاش آب"),
    ("zelle", "زيل", "زيلّي"),
    ("robinhood", "روبن هود"),
    ("coinbase", "كوين بيس"),
    ("walmart", "وول مارت", "والمارت"),
    ("target", "تارغت", "تارجت"),
    ("best buy", "بست باي"),
    ("costco", "كوستكو"),
    ("doordash", "door dash", "دور داش"),
    ("grubhub", "grub hub", "جرب هب"),
    ("instacart", "انستا كارت"),
    ("lyft", "ليفت"),
    ("hulu", "هولو"),
    ("peacock", "بيكوك"),
    ("paramount plus", "paramount+", "باراماونت بلس"),

    # UK
    ("barclays", "باركليز"),
    ("hsbc", "اتش اس بي سي", "إتش إس بي سي"),
    ("lloyds bank", "lloyds", "لويدز بنك"),
    ("natwest", "نات ويست"),
    ("halifax", "هاليفاكس"),
    ("monzo", "مونزو"),
    ("starling bank", "starling", "ستارلينغ بنك"),
    ("tesco", "تيسكو"),
    ("sainsburys", "sainsbury's", "سينزبريز"),
    ("asda", "اسدا", "أسدا"),
    ("deliveroo", "دليفرو"),
    ("just eat", "جست ايت"),
    ("bbc iplayer", "iplayer", "بي بي سي اي بلاير"),

    # CANADA
    ("rbc", "royal bank of canada", "ار بي سي", "رويال بنك اوف كندا"),
    ("td bank", "td canada trust", "تي دي بنك"),
    ("scotiabank", "scotia", "سكوشيا بنك"),
    ("bmo", "bank of montreal", "بي ام او", "بنك مونتريال"),
    ("cibc", "سي اي بي سي"),
    ("interac", "انتراك", "إنترآك"),
    ("tangerine", "تانجرين"),
    ("wealthsimple", "ويلث سمبل"),
    ("tim hortons", "تيم هورتنز"),
    ("skip the dishes", "سكيب ذا ديشز"),

    # TURKEY
    ("ziraat bankasi", "ziraat", "ziraat bank", "زراعت بنك", "بنك زراعت"),
    ("is bankasi", "is bank", "turkiye is bankasi", "iş bankası", "ايش بنك", "بنك ايش"),
    ("garanti bbva", "garanti", "غارانتي", "بنك غارانتي"),
    ("akbank", "اك بنك", "أك بنك"),
    ("yapi kredi", "yapı kredi", "يابي كريدي"),
    ("denizbank", "deniz bank", "دنيز بنك", "دينيز بنك"),
    ("vakifbank", "vakıfbank", "وقف بنك", "فاكيف بنك"),
    ("halkbank", "halk bank", "هالك بنك"),
    ("qnb finansbank", "finansbank", "كي ان بي فينانس بنك"),
    ("teb", "turk ekonomi bankasi", "تي اي بي"),
    ("papara", "بابارا"),
    ("ininal", "اينينال"),
    ("paycell", "بايسل", "باي سيل"),
    ("trendyol", "ترنديول"),
    ("hepsiburada", "hepsi burada", "هبسي بورادا"),
    ("n11", "n eleven", "ان 11", "إن 11"),
    ("getir", "جتير", "غتير"),
    ("yemeksepeti", "yemek sepeti", "يمك سبتي", "يَمَك سَبَتي"),
    ("migros", "ميغروس"),
    ("a101", "a 101", "اي 101"),
    ("bim", "بيم"),
    ("sok market", "şok", "شوك ماركت"),
    ("ciceksepeti", "çiçek sepeti", "تشيشك سبتي"),
    ("sahibinden", "صاحبندن", "صاحيبندن"),
    ("dolap", "دولاب"),
    ("letgo", "let go", "ليت جو"),
    ("pttavm", "ptt avm", "بي تي تي اي في ام"),
    ("turkcell", "ترك سل", "توركسل"),
    ("vodafone", "فودافون"),
    ("turk telekom", "türk telekom", "ترك تيليكوم"),
    ("bein connect", "بي ان كونكت"),
    ("exxen", "اكسن", "إكسن"),
    ("gain", "غين", "غاين"),
    ("blutv", "blue tv", "بلو تي في"),
    ("mhrs", "ام اتش ار اس"),
    ("e devlet", "edevlet", "e-devlet", "اي دولت", "إي دولت"),

    # SAUDI ARABIA
    ("al rajhi bank", "rajhi", "مصرف الراجحي", "الراجحي"),
    ("alinma bank", "بنك الانماء", "الانماء"),
    ("riyad bank", "بنك الرياض", "الرياض بنك"),
    ("saudi national bank", "snb", "البنك الاهلي السعودي", "الاهلي السعودي"),
    ("sabb", "ساب", "البنك السعودي البريطاني"),
    ("albilad bank", "bank albilad", "بنك البلاد", "البلاد"),
    ("stc pay", "اس تي سي باي", "stc باي", "اس تي سي"),
    ("urpay", "ur pay", "يور باي"),
    ("mada pay", "مدى باي"),
    ("absher", "أبشر", "ابشر"),
    ("nafath", "نفاذ"),
    ("tawakkalna", "توكلنا"),
    ("sehhaty", "صحتي"),
    ("najm", "نجم"),
    ("ejar", "إيجار", "ايجار"),
    ("hungerstation", "hunger station", "هنقرستيشن", "هنقر ستيشن"),
    ("jahez", "جاهز"),
    ("mrsool", "مرسول"),
    ("noon", "نون"),
    ("jarir", "jarir bookstore", "جرير", "مكتبة جرير"),
    ("extra", "extra stores", "اكسترا", "إكسترا"),
    ("nahdi", "nahdi pharmacy", "النهدي", "صيدلية النهدي"),
    ("almosafer", "المسافر"),
    ("haraj", "حراج"),

    # UAE
    ("emirates nbd", "بنك الإمارات دبي الوطني", "الإمارات دبي الوطني"),
    ("adcb", "abu dhabi commercial bank", "بنك أبوظبي التجاري", "ابوظبي التجاري"),
    ("fab", "first abu dhabi bank", "بنك أبوظبي الأول", "ابوظبي الاول"),
    ("mashreq", "mashreq bank", "المشرق", "بنك المشرق"),
    ("dubai islamic bank", "dib", "بنك دبي الإسلامي", "دبي الإسلامي"),
    ("careem", "كريم"),
    ("talabat", "طلبات"),
    ("noon uae", "نون الامارات", "نون الإمارات"),
    ("dubizzle", "دوبيزل"),
    ("bayut", "بيوت"),
    ("etisalat", "اتصالات"),
    ("du", "دو"),
    ("botim", "بوتيم"),
    ("payit", "pay it", "باي ات", "باي إت"),
    ("smiles", "سمايلز"),
    ("carrefour", "كارفور"),

    # EGYPT
    ("instapay", "انستا باي", "إنستا باي"),
    ("vodafone cash", "فودافون كاش"),
    ("fawry", "فوري"),
    ("meeza", "ميزة"),
    ("banque misr", "بنك مصر"),
    ("national bank of egypt", "nbe", "البنك الاهلي المصري", "الأهلي المصري"),
    ("cib egypt", "commercial international bank", "سي اي بي", "البنك التجاري الدولي"),
    ("qnb alahli", "qnb الأهلي", "كي يو ان بي الاهلي"),
    ("talabat egypt", "طلبات مصر"),
    ("elmenus", "المنيوز", "المنيوز"),
    ("jumia", "جوميا"),
    ("olx egypt", "olx", "او ال اكس", "أو إل إكس"),
    ("shahid", "شاهد", "شاهد vip", "شاهد في اي بي"),
    ("watch it", "watchit", "واتش ات", "واتش إت"),

    # KUWAIT / QATAR / BAHRAIN / OMAN / JORDAN / IRAQ / LEBANON
    ("kfh", "kuwait finance house", "بيت التمويل الكويتي", "بيتك"),
    ("nbk", "national bank of kuwait", "بنك الكويت الوطني", "الوطني"),
    ("knet", "كي نت"),
    ("carriage", "كاريج"),
    ("snoonu", "سنونو"),
    ("qnb", "qatar national bank", "بنك قطر الوطني"),
    ("ooredoo", "اوريدو", "أوريدو"),
    ("bbk", "bank of bahrain and kuwait", "بنك البحرين والكويت"),
    ("benefitpay", "benefit pay", "بنفت باي"),
    ("bank muscat", "بنك مسقط"),
    ("omantel", "عمانتل"),
    ("zain", "زين"),
    ("orange", "اورنج", "أورنج"),
    ("umniah", "امنية", "أمنية"),
    ("zain cash", "زين كاش"),
    ("jawaker", "جواكر"),
    ("toters", "توترز"),
    ("touch", "تاتش"),
    ("alfa", "الفا", "ألفا"),

    # ARABIC / MENA MEDIA & COMMON
    ("anghami", "انغامي", "أنغامي"),
    ("osn", "او اس ان", "أو إس إن"),
    ("yango", "يانغو", "يانجو"),
    ("imo", "ايمو", "إيمو"),
    ("truecaller", "true caller", "تروكولر", "ترو كولر"),

    ("istanbulkart", "istanbul kart", "İstanbulkart", "istanbul card", "اسطنبول كارت", "إسطنبول كارت", "كرت اسطنبول"),
    ("otobusum nerede", "otobüsüm nerede", "iett otobusum nerede", "iett", "اوتوبوسوم نيرده", "أوتوبوسوم نيرده", "ايتت"),
    ("iett", "i e t t", "iett mobil", "ايتت", "اي اي تي تي"),
    ("ulasim istanbul", "ulaşım istanbul", "metro istanbul", "مترو اسطنبول", "مواصلات اسطنبول"),
    ("moovit", "موفيت", "موڤيت"),
    ("bitaksi", "bi taksi", "بي تاكسي"),
    ("marti", "martı", "مارتي"),
    ("obilet", "o bilet", "او بيليت", "أوبيليت"),
    ("obilet", "otobus bileti", "otobüs bileti", "bus ticket", "تذكرة باص"),

    # ISLAM / QURAN / PRAYER APPS
    ("quran", "koran", "kuran", "kur'an", "qur'an", "القران", "القرآن", "قران", "قرآن", "مصحف"),
    ("holy quran", "the holy quran", "kuran-i kerim", "kuranı kerim", "القران الكريم", "القرآن الكريم", "المصحف الشريف"),
    ("quran majeed", "kuran mecid", "قرآن مجيد", "قران مجيد"),

    # MICROSOFT 365 MOBILE
    ("microsoft word", "word", "وورد", "مايكروسوفت وورد"),
    ("microsoft excel", "excel", "اكسل", "إكسل", "مايكروسوفت اكسل"),
    ("microsoft powerpoint", "powerpoint", "power point", "باوربوينت", "باور بوينت"),
    ("microsoft outlook", "outlook", "اوتلوك", "آوتلوك"),
    ("microsoft onedrive", "onedrive", "one drive", "ون درايف", "وان درايف"),
    ("microsoft onenote", "onenote", "one note", "ون نوت", "وان نوت"),
    (
        "microsoft authenticator",
        "authenticator",
        "authenticator app",
        "autenticator",
        "authentikator",
        "autentikator",
        "otantikator",
        "otentikator",
        "otantikatör",
        "otentikatör",
        "kimlik dogrulayici",
        "kimlik doğrulayıcı",
        "اوثنتيكيتور",
        "المصادق",
    ),

    # DEVELOPER / WORK MOBILE APPS
    ("github", "git hub", "جيت هب", "غيت هب", "جيتهاب"),
    ("gitlab", "git lab", "جيت لاب", "غيت لاب"),
    ("camscanner", "cam scanner", "كام سكانر"),

    # TURKEY EXTRA POPULAR SHOPPING / MARKET
    ("lc waikiki", "lcw", "ال سي وايكيكي"),
    ("defacto", "de facto", "ديفاكتو"),
    ("koton", "كوتون"),
    ("mavi", "مافي"),
    ("flo", "فلو"),
    ("gratis", "غراتيس"),

    # CRYPTO APPS
    ("binance", "بينانس", "باينانس"),
    ("coinbase", "كوين بيس", "كوينبيس"),
    ("kucoin", "كو كوين", "كوكوين"),
    ("kraken", "كراكن"),
    ("okx", "او كي اكس", "اوكي اكس"),
    ("bybit", "باي بيت", "بايبت"),
    ("gate io", "gateio", "غيت اي او"),
    ("crypto com", "crypto.com", "كريبتو كوم"),
    ("trust wallet", "trustwallet", "تراست والت", "محفظة تراست"),
    ("metamask", "meta mask", "ميتا ماسك"),
    ("blockchain", "blockchain wallet", "بلوكتشين", "محفظة بلوكتشين"),
    ("exodus", "اكسودس"),
    ("phantom", "فانتوم"),
    ("bitpanda", "بيت باندا"),
    ("rain", "رين", "rain crypto"),
    ("bitlo", "بيتلو"),
    ("paribu", "بارibu", "باربو"),
    ("btcturk", "btc turk", "بي تي سي تورك"),
    ("nexo", "نيكسو"),
    ("ledger live", "ledger", "ليدجر"),
    ("safe pal", "safepal", "سيف بال"),

    # VPN APPS
    ("turbo vpn", "توربو vpn", "توربو في بي ان"),
    ("vpn proxy master", "proxy master", "في بي ان بروكسي ماستر"),
    ("super vpn", "سوبر vpn", "سوبر في بي ان"),
    ("secure vpn", "سيكيور vpn", "سيكيور في بي ان"),
    ("expressvpn", "express vpn", "اكسبريس vpn", "اكسبريس في بي ان"),
    ("nordvpn", "nord vpn", "نورد vpn", "نورد في بي ان"),
    ("surfshark", "سيرف شارك", "سيرفشارك"),
    ("hotspot shield", "hotspot", "هوت سبوت شيلد"),
    ("proton vpn", "protonvpn", "بروتون vpn"),
    ("windscribe", "ويندسكرايب"),
    ("tunnelbear", "tunnel bear", "تانل بير"),
    ("hola vpn", "hola", "هولا vpn"),
    ("betternet", "better net", "بيتر نت"),
    ("psiphon", "سايفون", "psiphon vpn"),
    ("1.1.1.1", "warp", "cloudflare vpn", "وارب", "كلاودفلير vpn"),
    ("bingx", "bing x", "بينغ اكس", "بينج اكس", "بينغكس", "بينجكس"),
    ("bip", "bi p", "bip uygulamasi", "bip app", "بيپ", "بيب", "بي بي"),
]
