TRUNCATE TABLE command_history RESTART IDENTITY CASCADE;
TRUNCATE TABLE custom_commands RESTART IDENTITY CASCADE;
TRUNCATE TABLE custom_command_steps RESTART IDENTITY CASCADE;

TRUNCATE TABLE apps RESTART IDENTITY CASCADE;
TRUNCATE TABLE device_apps RESTART IDENTITY CASCADE;
TRUNCATE TABLE devices RESTART IDENTITY CASCADE;
TRUNCATE TABLE device_auth_credentials RESTART IDENTITY CASCADE;

TRUNCATE TABLE error_messages RESTART IDENTITY CASCADE;
TRUNCATE TABLE failed_app_open_attempts RESTART IDENTITY CASCADE;