from V3.patterns.commands.display import BRIGHTNESS_PATTERNS
from V3.patterns.commands.contact import CALL_CONTACT_PATTERNS
from V3.patterns.commands.system_settings import (
    SOUND_MODE_PATTERNS,
    STATE_INTENT_PATTERNS
)
from V3.patterns.commands.timer import (
    TIMER_ACTION_PATTERNS,
    TIMER_KEYWORDS
)
from V3.patterns.commands.volume import (
    VOLUME_LEVEL_PATTERNS,
    VOLUME_PATTERNS
)
from V3.patterns.commands.guards import (
    AMBIGUOUS_PATTERNS,
    DEFERRED_PATTERNS,
    NEGATION_PATTERNS
)
from V3.patterns.commands.text_controls import (
    CLEAR_TEXT_PATTERNS,
    DOUBLE_TAP_PATTERNS,
    HOLD_SCREEN_PATTERNS
)
from V3.patterns.commands.gestures import (
    SCROLL_DOWN_PATTERNS,
    SCROLL_UP_PATTERNS,
    SWIPE_LEFT_PATTERNS,
    SWIPE_RIGHT_PATTERNS,
)
from V3.patterns.commands.app import (
    APP_SUFFIX_SEPARATORS,
    OPEN_APP_PATTERNS,
    OPEN_APP_REJECT_PATTERNS,
    REJECT_APP_NAMES
)
from V3.patterns.commands.navigation import (
    CLOSE_APP_PATTERNS,
    GO_BACK_PATTERNS,
    GO_HOME_PATTERNS,
    OPEN_NOTIFICATIONS_PATTERNS,
    SHOW_RECENTS_PATTERNS,
    STOP_LISTENING_PATTERNS,
    TAKE_PHOTO_PATTERNS,
    TAKE_SCREENSHOT_PATTERNS,
)

__all__ = [
    "AMBIGUOUS_PATTERNS",
    "APP_SUFFIX_SEPARATORS",
    "BRIGHTNESS_PATTERNS",
    "CALL_CONTACT_PATTERNS",
    "CLEAR_TEXT_PATTERNS",
    "CLOSE_APP_PATTERNS",
    "DEFERRED_PATTERNS",
    "DOUBLE_TAP_PATTERNS",
    "GO_BACK_PATTERNS",
    "GO_HOME_PATTERNS",
    "HOLD_SCREEN_PATTERNS",
    "NEGATION_PATTERNS",
    "OPEN_APP_PATTERNS",
    "OPEN_APP_REJECT_PATTERNS",
    "OPEN_NOTIFICATIONS_PATTERNS",
    "REJECT_APP_NAMES",
    "SCROLL_DOWN_PATTERNS",
    "SCROLL_UP_PATTERNS",
    "SHOW_RECENTS_PATTERNS",
    "SOUND_MODE_PATTERNS",
    "STATE_INTENT_PATTERNS",
    "STOP_LISTENING_PATTERNS",
    "SWIPE_LEFT_PATTERNS",
    "SWIPE_RIGHT_PATTERNS",
    "TAKE_PHOTO_PATTERNS",
    "TAKE_SCREENSHOT_PATTERNS",
    "TIMER_ACTION_PATTERNS",
    "TIMER_KEYWORDS",
    "VOLUME_PATTERNS",
    "VOLUME_LEVEL_PATTERNS",
]
