BRIGHTNESS_PATTERNS = {
    "increase": {
        "EN": [
            "increase brightness",
            "brightness up",
            "brighten display",
            "brighten the display",
            "make screen brighter",
            "raise brightness",
        ],
        "TR": [
            "parlakligi yukselt",
            "parlakligi artir",
            "ekran parlakligini artir",
            "ekran parlakligini yukselt",
            "parlakligi ac",
            "ekran isigini yukselt",
            "ekran isigini ac",
            "isigi biraz ac",
        ],
        "AR": [
            "ارفع السطوع",
            "زود السطوع",
            "اجعل الشاشة اكثر سطوعا",
            "سطوع اعلى",
            "ارفع اضاءة الشاشة",
        ],
    },
    "decrease": {
        "EN": [
            "decrease brightness",
            "brightness down",
            "lower brightness",
            "dim display",
            "dim the display",
            "make screen darker",
        ],
        "TR": [
            "parlakligi azalt",
            "parlakligi dusur",
            "ekran parlakligini azalt",
            "ekran daha los olsun",
            "ekrani karart",
            "ekran isigini dusur",
            "ekran isigini kis",
        ],
        "AR": [
            "اخفض السطوع",
            "قلل السطوع",
            "اجعل الشاشة اغمق",
            "سطوع اقل",
            "اخفض اضاءة الشاشة",
        ],
    },
}
