CLEAR_TEXT_PATTERNS = {
    "EN": [
        "clear text",
        "clear the text",
        "clear input",
        "clear the input",
        "erase text",
        "erase the text",
        "delete text",
        "delete what i wrote",
        "delete what i have written",
        "delete what you wrote",
        "delete what you have written",
        "erase what i wrote",
        "erase what i have written",
        "clear what i wrote",
        "clear what i have written",
    ],
    "TR": [
        "metni temizle",
        "metni sil",
        "yaziyi temizle",
        "yaziyi sil",
        "inputu temizle",
    ],
    "AR": [
        "امسح النص",
        "احذف النص",
        "نظف النص",
        "امسح الكتابة",
        "امسح حقل الكتابة",
    ],
}

FOCUS_INPUT_PATTERNS = {
    "EN": [
        "focus input",
        "focus the input",
        "focus on the input",
        "focus on text field",
        "focus on the text field",
        "focus on the field",
        "focus on inputs",
        "focus on the inputs",
        "focus text field",
        "focus the text field",
        "focus the inputs",
        "focus the field",
        "focus Imports",
        "focus the import",
        "select input field",
        "select the input field",
        "select text field",
        "select the text field",
        "select the inputs",
        "select the imports",
        "select inputs",
        "select input",
        "select field",
        "activate input",
        "activate text field",
        "place cursor",
        "place the cursor",
        "place cursor in input",
        "place cursor in text field",
    ],
    "TR": [
        "inputa odaklan",
        "input alanina odaklan",
        "metin alanina odaklan",
        "yazi alanina odaklan",
        "yazi kutusuna odaklan",
        "input alanini sec",
        "metin alanini sec",
        "yazi alanini sec",
        "imleci alana getir",
        "imleci metin alanina getir",
    ],
    "AR": [
        "ركز على الحقل",
        "ركز على حقل النص",
        "حدد حقل النص",
        "حدد خانة النص",
        "افتح حقل النص",
        "ضع المؤشر",
        "ضع المؤشر في الحقل",
        "ضع المؤشر في حقل النص",
    ],
}

UNFOCUS_INPUT_PATTERNS = {
    "EN": [
        "unfocus",
        "unfocused",
        "unfocus input",
        "unfocused input",
        "unfocus inputs",
        "unfocused inputs",
        "unfocus the input",
        "unfocused the input",
        "unfocus text",
        "unfocused text",
        "unfocus the text",
        "unfocused the text",
        "unfocus text field",
        "unfocused text field",
        "unfocus the text field",
        "unfocused the text field",
        "unfocus input field",
        "unfocused input field",
        "unfocus the input field",
        "unfocused the input field",
        "clear focus",
        "cleared focus",
        "clear the focus",
        "cleared the focus",
        "remove focus",
        "removed focus",
        "remove the focus",
        "removed the focus",
        "leave text field",
        "left text field",
        "leave the text field",
        "left the text field",
        "exit text field",
        "exited text field",
        "exit the text field",
        "exited the text field",
    ],
    "TR": [
        "odagi kaldir",
        "fokusu kaldir",
        "inputtan cik",
        "input alanindan cik",
        "metin alanindan cik",
        "yazi alanindan cik",
    ],
    "AR": [
        "الغ التركيز",
        "ازل التركيز",
        "اخرج من الحقل",
        "اخرج من حقل النص",
    ],
}

DOUBLE_TAP_PATTERNS = {
    "EN": [
        "double tap",
        "double tap screen",
        "double tap the screen",
        "tap twice",
    ],
    "TR": [
        "ekrana cift tikla",
        "ekrani cift tikla",
        "cift tikla",
        "iki kere tikla",
    ],
    "AR": [
        "انقر مرتين",
        "اضغط مرتين",
        "اضغط على الشاشة مرتين",
        "دبل كليك",
    ],
}

HOLD_SCREEN_PATTERNS = {
    "EN": [
        "long press",
        "long press screen",
        "press and hold",
        "hold screen",
        "hold on the screen",
    ],
    "TR": [
        "ekrana basili tut",
        "ekrani basili tut",
        "basili tut",
        "uzun bas",
    ],
    "AR": [
        "اضغط مطولا",
        "اضغط باستمرار",
        "اضغط مع الاستمرار",
        "اضغط على الشاشة باستمرار",
        "ثبت الضغط",
    ],
}
