TIMER_KEYWORDS = {
    "EN": [
        "timer",
        "countdown",
        "count down",
        "timing",
    ],
    "TR": [
        "zamanlayici",
        "sayac",
        "geri say",
        "sure tut",
        "zaman tut",
    ],
    "AR": [
        "مؤقت",
        "موقت",
        "منبه",
        "عداد",
        "عد تنازلي",
        "توقيت",
    ],
}

TIMER_ACTION_PATTERNS = {
    "EN": [
        "set timer",
        "set a timer",
        "start timer",
        "start a timer",
        "start timing",
        "run a timer",
        "make a timer",
        "create a timer",
        "begin countdown",
        "start countdown",
        "count down",
    ],
    "TR": [
        "zamanlayici kur",
        "zamanlayici ayarla",
        "zamanlayici olustur",
        "sayac kur",
        "sayac baslat",
        "geri sayim baslat",
        "geri say",
        "sure tut",
        "zaman tut",
    ],
    "AR": [
        "اضبط مؤقت",
        "ابدأ مؤقت",
        "ابدا مؤقت",
        "شغل مؤقت",
        "انشئ مؤقت",
        "أنشئ مؤقت",
        "ابدأ عد تنازلي",
        "شغل عداد",
    ],
}
