TIMER_KEYWORDS = [
    "timer",
    "countdown",
    "count down",
    "timing",
    "zamanlayici",
    "sayac",
    "geri say",
    "sure tut",
    "zaman tut",
]

TIMER_ACTION_PATTERNS = [
    "set timer",
    "set a timer",
    "start timer",
    "start a timer",
    "start timing",
    "run a timer",
    "make a timer",
    "create a timer",
    "begin countdown",
    "start countdown",
    "count down",
    "zamanlayici kur",
    "zamanlayici ayarla",
    "zamanlayici olustur",
    "sayac kur",
    "sayac baslat",
    "geri sayim baslat",
    "geri say",
    "sure tut",
    "zaman tut",
]
