VOLUME_PATTERNS = {
    "decrease": [
        "decrease volume",
        "decrease the volume",
        "decrease sound",
        "decrease the sound",
        "lower volume",
        "lower the volume",
        "lower sound",
        "lower the sound",
        "volume down",
        "sound down",
        "turn volume down",
        "turn the volume down",
        "turn sound down",
        "turn the sound down",
        "sesi azalt",
        "ses azalt",
        "sesi kis",
        "ses kis",
        "ses seviyesini azalt",
        "ses seviyesini dusur",
        "sesi dusur",
    ],
    "increase": [
        "increase volume",
        "increase the volume",
        "increase sound",
        "increase the sound",
        "raise volume",
        "raise the volume",
        "raise sound",
        "raise the sound",
        "volume up",
        "sound up",
        "turn volume up",
        "turn the volume up",
        "turn sound up",
        "turn the sound up",
        "sesi artir",
        "ses artir",
        "sesi arttir",
        "ses arttir",
        "sesi yukselt",
        "ses yukselt",
        "ses seviyesini artir",
        "ses seviyesini yukselt",
        "sesi ac",
    ],
    "mute": [
        "mute sound",
        "mute the sound",
        "mute audio",
        "turn off sound",
        "turn off the sound",
        "silence phone",
        "silence the phone",
        "sesi kapat",
        "sesi sustur",
        "sessize al",
        "telefonu sessize al",
    ],
    "unmute": [
        "unmute sound",
        "unmute the sound",
        "unmute audio",
        "turn sound back on",
        "turn the sound back on",
        "enable sound",
        "sessizi kaldir",
        "sesi geri ac",
        "telefonun sesini geri ac",
    ],
}
