VOLUME_PATTERNS = {
    "decrease": {
        "EN": [
            "decrease volume",
            "decrease the volume",
            "decrease sound",
            "decrease the sound",
            "lower volume",
            "lower the volume",
            "lower sound",
            "lower the sound",
            "volume down",
            "sound down",
            "turn volume down",
            "turn the volume down",
            "turn sound down",
            "turn the sound down",
        ],
        "TR": [
            "sesi azalt",
            "ses azalt",
            "sesi kis",
            "ses kis",
            "ses seviyesini azalt",
            "ses seviyesini dusur",
            "sesi dusur",
        ],
        "AR": [
            "اخفض الصوت",
            "خفض الصوت",
            "قلل الصوت",
            "نزل الصوت",
        ],
    },
    "increase": {
        "EN": [
            "increase volume",
            "increase the volume",
            "increase sound",
            "increase the sound",
            "raise volume",
            "raise the volume",
            "raise sound",
            "raise the sound",
            "volume up",
            "sound up",
            "turn volume up",
            "turn the volume up",
            "turn sound up",
            "turn the sound up",
        ],
        "TR": [
            "sesi artir",
            "ses artir",
            "sesi arttir",
            "ses arttir",
            "sesi yukselt",
            "ses yukselt",
            "ses seviyesini artir",
            "ses seviyesini yukselt",
            "sesi ac",
            "sesini ac",
            "aktif medya sesini ac",
        ],
        "AR": [
            "ارفع الصوت",
            "رفع الصوت",
            "زيد الصوت",
            "علي الصوت",
        ],
    },
    "mute": {
        "EN": [
            "mute sound",
            "mute the sound",
            "mute audio",
            "turn off sound",
            "turn off the sound",
            "silence phone",
            "silence the phone",
        ],
        "TR": [
            "sesi kapat",
            "sesi sustur",
        ],
        "AR": [
            "اكتم الصوت",
            "اغلق الصوت",
            "اجعل الهاتف صامت",
            "حول الهاتف إلى صامت",
        ],
    },
    "unmute": {
        "EN": [
            "unmute sound",
            "unmute the sound",
            "unmute audio",
            "turn sound back on",
            "turn the sound back on",
            "enable sound",
        ],
        "TR": [
            "sessizi kaldir",
            "sesi geri ac",
            "sesi yeniden ac",
            "medya sesini geri ac",
            "ses cikisini geri ac",
            "telefonun sesini geri ac",
        ],
        "AR": [
            "افتح الصوت",
            "الغ كتم الصوت",
            "ارجع الصوت",
            "شغل الصوت مرة اخرى",
            "شغل الصوت من جديد",
            "افتح صوت الميديا من جديد",
        ],
    },
}

VOLUME_LEVEL_PATTERNS = {
    "low": {
        "EN": [
            "set volume low",
            "set the volume low",
            "low volume",
            "volume low",
            "set sound low",
        ],
        "TR": [
            "sesi dusuk yap",
            "sesi kisik yap",
            "ses seviyesini dusuk yap",
        ],
        "AR": [
            "اجعل الصوت منخفض",
            "الصوت منخفض",
            "صوت منخفض",
        ],
    },
    "medium": {
        "EN": [
            "set volume medium",
            "set the volume medium",
            "medium volume",
            "volume medium",
            "set sound medium",
        ],
        "TR": [
            "sesi orta yap",
            "ses seviyesini orta yap",
        ],
        "AR": [
            "اجعل الصوت متوسط",
            "الصوت متوسط",
            "صوت متوسط",
        ],
    },
    "max": {
        "EN": [
            "set volume max",
            "set the volume max",
            "max volume",
            "maximum volume",
            "volume max",
            "set volume high",
            "set the volume high",
            "high volume",
            "volume high",
            "set sound max",
            "set sound maximum",
            "set sound high",
        ],
        "TR": [
            "sesi maksimum yap",
            "sesi max yap",
            "ses seviyesini maksimum yap",
            "ses seviyesini max yap",
            "sesi yuksek yap",
            "ses seviyesini yuksek yap",
        ],
        "AR": [
            "اجعل الصوت اقصى",
            "اجعل الصوت اعلى شيء",
            "الصوت على الاخر",
            "صوت عالي",
        ],
    },
}
